#!/bin/sh

ptton()
{
    #PTT on GPIO 0 AND GPIO 2 (GPIO 1 should be not touched)
	echo 0 > /sys/bus/iio/devices/iio:device1/out_altvoltage1_TX_LO_powerdown
	echo 0x27 0x50 > /sys/kernel/debug/iio/iio:device1/direct_reg_access
	mosquitto_pub -t plutodvb/status/tx -m true
}

pttoff()
{
		echo 1 > /sys/bus/iio/devices/iio:device1/out_altvoltage1_TX_LO_powerdown
        echo 0x27 0x00 > /sys/kernel/debug/iio/iio:device1/direct_reg_access
		mosquitto_pub -t plutodvb/status/tx -m false
}

start() {

if [ -f "/mnt/jffs2/etc/settings-receiver.txt" ]; then
	cp /mnt/jffs2/etc/settings-receiver.txt /www/
fi

if [ -f "/mnt/jffs2/etc/settings.txt" ]; then   
   cp /mnt/jffs2/etc/settings.txt /www/settings.txt 
else
	/root/readconfig_from_env.sh >/dev/null </dev/null 2>/dev/null
	cp /www/settings.txt /mnt/jffs2/etc/settings.txt 
fi 
 
 
   CONF=/mnt/jffs2/etc/settings-datv.txt
   	MAINMODE=$(grep mainmode $CONF | cut -f2 -d '='|sed 's/ //g')
	DATVMODE=$(grep datvmode $CONF | cut -f2 -d '='|sed 's/ //g')
	TXSTART=$(grep tx_onstart $CONF | cut -f2 -d '='|sed 's/ //g')
    REMUX=$(grep remux $CONF | cut -f2 -d '='|sed 's/ //g')
	if [ "$MAINMODE" = "" ]; then
		MAINMODE=pass
		echo -e "mainmode = pass\n" >> $CONF
		echo -e "[DATV]\n" >> $CONF
		echo -e "datvmode = rtmp\n" >> $CONF
		echo -e "remux = on\n" >> $CONF
		
	fi
	


	if [ "$MAINMODE" = "datv" ]; then
		if [ "$TXSTART" = "on" ]; then
			ptton
		else
			pttoff
		fi

		if [ "$DATVMODE" = "udp" ]; then
				/root/udpts.sh >/dev/null </dev/null 2>/dev/null &
				/root/watchudp.sh >/dev/null </dev/null 2>/dev/null &
				/root/dynamic_h265box.sh >/dev/null </dev/null 2>/dev/null & 
		fi
		if [ "$DATVMODE" = "rtmp" ]; then
			/root/rtmppluto.sh >/dev/null </dev/null 2>/dev/null &
		fi
		if [ "$DATVMODE" = "test" ]; then
#			 /root/testpatern.sh >/dev/null </dev/null 2>/dev/null &
        /root/pluto_fft_ws >/dev/null </dev/null 2>/dev/null &
		fi
	else
		/root/watchconsoletx.sh </dev/null 2>/dev/null &
		ptton
		echo mode passthrough
	fi
	mosquitto_pub -t plutodvb/started -m true
	
    

#/root/decodevideo.sh >/dev/null </dev/null 2>/dev/null &  
}

stop() {
	echo heartbeat > /sys/class/leds/led0:green/trigger
	#Be sure to stop tx
	pttoff
	mosquitto_pub -t plutodvb/started -m false

	#kill all the processes
	# UDP
	pkill watchudp
	pkill udpts
	pkill pluto_dvb
	pkill tsp
	pkill dynamic_h265box
	pkill tsvbr2cbr

	# RTMP  
	pkill rtmppluto

	#patern
	pkill testpatern
	#passthrough
	pkill watchconsoletx
	
	#common
	
	pkill ffmpeg

	# Do a standard Pluto for external software
	echo 3000000 > /sys/bus/iio/devices/iio:device1/out_voltage_sampling_frequency
	sleep 0.1
	echo 3000000 > /sys/bus/iio/devices/iio:device4/in_voltage_sampling_frequency
	sleep 0.1
	echo 3000000 > /sys/bus/iio/devices/iio:device3/out_voltage_sampling_frequency
	sleep 0.1
	echo 1 > /sys/bus/iio/devices/iio:device1/in_out_voltage_filter_fir_en
	sleep 0.1
	echo 0 > /sys/bus/iio/devices/iio:device1/out_altvoltage1_TX_LO_powerdown
	sleep 0.1
	echo 0 > /sys/bus/iio/devices/iio:device1/out_altvoltage0_RX_LO_powerdown
	sleep 0.1
	echo 0 > /sys/kernel/debug/iio/iio:device1/loopback
	sleep 0.1
	echo "Stopping"
}

restart() {
	stop
	start
}

# start/stop/restart
case "$1" in
  start)
    printf "Starting DATV: "
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


