#!/bin/sh

start() {

/root/readsensor.sh >/dev/null </dev/null 2>/dev/null &
/root/switchmod.sh </dev/null 2>/dev/null &


}

stop() {

	echo "Stopping"
}

restart() {
	stop
	start
}

# start/stop/restart
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


